[2023-04-14T21:09:45.510+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tutorial_2_amir.print_date scheduled__2023-04-13T21:09:25.854577+00:00 [queued]>
[2023-04-14T21:09:45.518+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tutorial_2_amir.print_date scheduled__2023-04-13T21:09:25.854577+00:00 [queued]>
[2023-04-14T21:09:45.518+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T21:09:45.518+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-14T21:09:45.519+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T21:09:45.529+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): print_date> on 2023-04-13 21:09:25.854577+00:00
[2023-04-14T21:09:45.533+0000] {standard_task_runner.py:55} INFO - Started process 92 to run task
[2023-04-14T21:09:45.537+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tutorial_2_amir', 'print_date', 'scheduled__2023-04-13T21:09:25.854577+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp0zhmf9pd']
[2023-04-14T21:09:45.538+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask print_date
[2023-04-14T21:09:45.549+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-04-14T21:09:45.565+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-04-14T21:09:45.589+0000] {task_command.py:389} INFO - Running <TaskInstance: tutorial_2_amir.print_date scheduled__2023-04-13T21:09:25.854577+00:00 [running]> on host 4a2434575694
[2023-04-14T21:09:45.637+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_2_amir
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T21:09:25.854577+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-13T21:09:25.854577+00:00
[2023-04-14T21:09:45.638+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T21:09:45.640+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'date']
[2023-04-14T21:09:45.652+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T21:09:45.654+0000] {subprocess.py:93} INFO - Fri Apr 14 21:09:45 UTC 2023
[2023-04-14T21:09:45.654+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-04-14T21:09:45.675+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=tutorial_2_amir, task_id=print_date, execution_date=20230413T210925, start_date=20230414T210945, end_date=20230414T210945
[2023-04-14T21:09:45.707+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-14T21:09:45.725+0000] {taskinstance.py:2596} INFO - 2 downstream tasks scheduled from follow-on schedule check
